import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  section: {
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  title: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  description: { fontSize: 14, lineHeight: 19, marginTop: 0, marginBottom: 10 },
  heading: { fontSize: 17, fontWeight: '700', marginTop: 17, marginBottom: 10 },
  options: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  advancedToggle: { alignSelf: 'flex-start', marginTop: 10 },
  customColorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 11,
  },
  customColorLabel: { fontSize: 13, minWidth: 145 },
  colorInput: {
    width: 150,
    minHeight: 52,
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 17,
  },
  focusedInput: { borderWidth: 3 },
  colorHint: { fontSize: 12, marginTop: 7 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    minHeight: 52,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderWidth: 1.5,
    borderRadius: 12,
  },
  layoutOption: {
    width: '48%',
    minWidth: 250,
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 6,
  },
  preview: { width: '100%', height: 90, borderRadius: 8, padding: 6, gap: 4 },
  previewImage: { ...StyleSheet.absoluteFill, borderRadius: 8 },
  largePreview: { height: 188, padding: 9, gap: 7 },
  previewRow: { flexDirection: 'row', gap: 4 },
  previewTile: {
    minWidth: 0,
    borderRadius: 5,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  previewLabel: { fontSize: 9, fontWeight: '700' },
  largePreviewLabel: { fontSize: 12 },
  focused: { transform: [{ scale: 1.04 }] },
  optionLabel: { fontSize: 16, fontWeight: '700' },
  optionSubtitle: { fontSize: 12, maxWidth: 200, marginTop: 2 },
  swatch: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  cardEditor: { gap: 18, alignItems: 'flex-start' },
  cardList: { gap: 8, minWidth: 0 },
  livePreviewPanel: { borderWidth: 1.5, borderRadius: 16, padding: 15 },
  livePreviewTitle: { fontSize: 16, fontWeight: '700' },
  livePreviewMeta: { fontSize: 12, marginTop: 4, marginBottom: 8 },
  livePreviewHint: { fontSize: 12, lineHeight: 18, marginTop: 9 },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
  },
  cardName: { fontSize: 15, fontWeight: '700', minWidth: 110, flexShrink: 1, maxWidth: '100%' },
  cardActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  reset: { marginTop: 17, alignSelf: 'flex-start' },
});

